[package]
name = "rock"
version = "0.1.0"
authors = ["Valery Piashchynski <piashchynski_valery@hotmail.com>"]
homepage = "https://spiralscout.com"
repository = "https://github.com/spiral/rock.git"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "rock"
path = "src/lib.rs"
crate-type = ["rlib"]

[workspace]
members = [
  ".",
  "rock_parser",
  "rock_reports",
  "rock_server",
  "rock_utils"
]

[dependencies]
actix-web = "3.0.0-alpha.1"
actix-rt = "1.1.1"
chrono = "0.4.11"
flate2 = "1.0.14"
nom = "5.1"
rock_parser = {path = "./rock_parser"}
rock_reports = {path = "./rock_reports"}
rock_server = {path = "./rock_server"}
rock_utils = {path = "./rock_utils"}

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 16
rpath = false

[profile.release]
opt-level = 3
lto = "fat"
debug = false
debug-assertions = false
overflow-checks = false
panic = 'unwind'
incremental = false
rpath = false
codegen-units = 1
