name: CI

on:
  pull_request: {}
  push:
    branches:
      - staging
      - trying
      - master

env:
  RUST_BACKTRACE: full

jobs:
  style:
    name: Check Style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          profile: default
          override: true

      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./proto_core/Cargo.toml --all -- --check

  clippy_check:
    name: Clippy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path ./proto_core/Cargo.toml --all-targets --all-features -- -D warnings

  build:
    name: ${{ matrix.name }}
    needs: [style]

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        name:
          - linux / stable
          - linux / beta

        include:
          - name: linux / stable
            os: ubuntu-latest
            rust: stable
          - name: linux / beta
            os: ubuntu-latest
            rust: beta

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: default
          override: true

      - name: Build proto_core
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./proto_core/Cargo.toml

      - name: Build launcher
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./launcher/Cargo.toml

      - name: Build http server
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./http_server/Cargo.toml

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./proto_core/Cargo.toml